version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: master
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: master
    labels:
      - dependencies
    groups:
      codeql-action:
        applies-to: version-updates
        patterns:
          - "github/codeql-action"
          - "github/codeql-action/*"
